name: Renovate Self-Hosted

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set Yarn as default package manager
        run: echo "YARN_ENABLE_SCRIPTS=0" >> $GITHUB_ENV

      - name: Install dependencies using Yarn
        run: yarn install --frozen-lockfile

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.9
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate-config.json
