name: Update Cache Version on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update-cache-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get the current version of the cache
      id: get-version
      run: |
        version=$(grep -oP 'const version = \K\d+' src/teste.ts | sort -n | tail -n 1)
        echo "version=$version" >> $GITHUB_ENV

    - name: Increment the cache version
      id: increment-version
      run: |
        new_version=$((version + 1))
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "New cache version: v$new_version"

    - name: Update version in the code
      run: |
        sed -i "s/const version = ${version}/const version = ${new_version}/g" src/teste.ts

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/teste.ts
        git commit -m "Increment cache version to v${{ env.new_version }}"
        git pull origin ${{ github.head_ref }} --rebase
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.head_ref }}
